urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
import settings

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'views.home', name='home'),
    url(r'^pedir_taxi/$', 'apps.taxi.views.pedidoTaxi'),
    # url(r'^generic_django_project/', include('generic_django_project.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

)

apps/taxi/models.py
from datetime import datetime
from django.db import models


class Taxi(models.Model):

    nome = models.CharField('Nome', max_length=100)
    telefone = models.CharField(max_length=14)
    dt_pedido = models.DateTimeField('Data do Pedido', default=datetime.now)

    class Meta:
        verbose_name = 'Pedido de Taxi'
        verbose_name_plural = 'Pedidos de Taxi'

    def __unicode__(self):
        return self.nome

templates/tservice/index.html
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>tservice</title>

  <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/foundation.css">
   <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/anime.css">
  <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/jsKeyboard.css">
  <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/estilo.css">
  <script src="{{ MEDIA_URL }}javascripts/modernizr.foundation.js"></script>
  <script src="{{ MEDIA_URL }}javascripts/modernizr.custom.js"></script>
</head>

<body class="home">

  <div id="header-slide">
    <div id="slider">
      {% for slide in slides %}
      <img src="{{ MEDIA_URL }}{{ slide.imagem }}" />
      {% endfor %}
    </div>
  </div>


  <section id="conteudo">

  <header id="header">
      <div class="row">
        <div class="two columns">
          <h1><a href=""><img src="{{ MEDIA_URL }}images/logo.png"></a></h1>
        </div>
      </div>
  </header>

  <div class="row">
    <div class="twelve columns">
      <div id="bl-main" class="bl-main">
        <section>
          <div class="bl-box">
            <h3><img src="{{ MEDIA_URL }}images/icone1.png" alt=""></h3>
            <h2>Check-in de vôos</h2>
          </div>
          <div class="bl-content">
            <div class="header-title">
              <div class="row">
                <div class="eleven columns">
                  <figure><img src="{{ MEDIA_URL }}images/icone1.png"></figure>
                  <h3>Check-in de vôo</h3>
                </div>

                <div class="one columns">
                    <h2><span class="bl-icon-close"></span></h2>
                </div>
              </div>
            </div>
            <div class="row">
            {% for companhia in companhias %}
              {% if forloop.last %}
              <div class="four columns end">
             {% else %}
              <div class="four columns">
             {% endif %}
                <div class="bloco bg-green">
                  <a href="{{ companhia.link }}" target="_blank">
                    <img src="{{ companhia.get_thumb }}" alt="{{ companhia.nome }}">
                  </a>
                </div>
              </div>
            {% endfor %}

            </div>
          </div>
        </section>

        <section>
          <div class="bl-box">
            <h3><img src="{{ MEDIA_URL }}images/icone2.png" alt=""></h3>
            <h2 class="">Solicitar taxi</h2>
          </div>
          <div class="bl-content">
            <div class="header-title">
              <div class="row">
                <div class="eleven columns">
                  <figure><img src="{{ MEDIA_URL }}images/icone2.png"></figure>
                  <h3>Solicitar taxi</h3>
                </div>

                <div class="one columns">
                    <h2><span class="bl-icon-close"></span></h2>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="six columns">
                <h4>Preencha o formulario</h4>
                <form method="POST" action="{% url 'apps.taxi.views.pedidoTaxi' %}">
                  {% csrf_token %}
                  {{ form.non_field_errors }}
                  <label for="id_nome">Nome:</label>
                  <input id="nome" name="nome" type="text" class="twelve" onfocus="jsKeyboard.focus(this);">

                  <label for="id_telefone">Telefone:</label>
                  <input id="id_telefone" name="telefone" type="text" class="seven" onfocus="jsKeyboard.focus(this);">

                  <input type="submit" class="btn" value="Solicitar" />
                </form>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div class="bl-box">
            <h3><img src="{{ MEDIA_URL }}images/icone3.png" alt=""></h3>
            <h2 class="">Onde comer</h2>
          </div>
          <div class="bl-content">
            <div class="header-title">
              <div class="row">
                <div class="eleven columns">
                  <figure><img src="{{ MEDIA_URL }}images/icone3.png"></figure>
                  <h3>Onde comer</h3>
                </div>

                <div class="one columns">
                    <h2><span class="bl-icon-close"></span></h2>
                </div>
              </div>
            </div>

            <div class="row">
            {% for restaurante in restaurantes %}
             {% if forloop.last %}
              <div class="three columns end">
             {% else %}
              <div class="three columns">
             {% endif %}
                <div class="bloco bg-roxo">
                  <a href="http://checkininternet.voegol.com.br/in" target="_blank">
                    <img src="{{ restaurante.get_thumb }}" alt="{{ restaurante.nome }}">
                  </a>
                </div>
              </div>
            {% endfor %}

            </div>
        </section>

        <section>
          <div class="bl-box">
            <h3><img src="{{ MEDIA_URL }}images/icone4.png" alt=""></h3>
            <h2 class="">Solicitar carro</h2>
          </div>
          <div class="bl-content">
            <div class="header-title">
              <div class="row">
                <div class="eleven columns">
                  <figure><img src="{{ MEDIA_URL }}images/icone4.png"></figure>
                  <h3>Solicitar carro</h3>
                </div>

                <div class="one columns">
                    <h2><span class="bl-icon-close"></span></h2>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="six columns">
                <h4>Preencha o formulario</h4>
                <form>
                  <label>Nome:</label>
                  <input type="text" class="twelve" onfocus="jsKeyboard.focus(this);">

                  <label>Telefone:</label>
                  <input type="text" class="seven" onfocus="jsKeyboard.focus(this);">

                  <a class="btn" href="#">Solicitar</a>
                </form>
              </div>
            </div>
          </div>
          <span class="bl-icon-close"></span>
        </section>

        <section>
          <div class="bl-box">
            <h3><img src="{{ MEDIA_URL }}images/icone5.png" alt=""></h3>
            <h2 class="">Onde comprar</h2>
          </div>
          <div class="bl-content">
             <div class="header-title">
               <div class="row">
                 <div class="eleven columns">
                   <figure><img src="{{ MEDIA_URL }}images/icone5.png"></figure>
                   <h3>Onde comprar</h3>
                 </div>

                 <div class="one columns">
                     <h2><span class="bl-icon-close"></span></h2>
                 </div>
               </div>
             </div>

             <div class="row">
               <div class="six columns">
                 <h4>Preencha o formulario</h4>
                 <form>
                   <label>Nome:</label>
                   <input type="text" class="twelve" onfocus="jsKeyboard.focus(this);">

                   <label>Telefone:</label>
                   <input type="text" class="seven" onfocus="jsKeyboard.focus(this);">

                   <a class="btn" href="#">Solicitar</a>
                 </form>
               </div>
             </div>
          </div>
        </section>

        <section>
          <div class="bl-box">
            <h3><img src="{{ MEDIA_URL }}images/icone6.png" alt=""></h3>
            <h2 class="">+ Info</h2>
          </div>
          <div class="bl-content">
             <div class="header-title">
               <div class="row">
                 <div class="eleven columns">
                   <figure><img src="{{ MEDIA_URL }}images/icone6.png"></figure>
                   <h3>+ Info</h3>
                 </div>

                 <div class="one columns">
                     <h2><span class="bl-icon-close"></span></h2>
                 </div>
               </div>
             </div>

             <div class="row">
               <div class="six columns">
                 <h4>Preencha o formulario</h4>
                 <form>
                   <label>Nome:</label>
                   <input type="text" class="twelve" onfocus="jsKeyboard.focus(this);">

                   <label>Telefone:</label>
                   <input type="text" class="seven" onfocus="jsKeyboard.focus(this);">

                   <a class="btn" href="#">Solicitar</a>
                 </form>
               </div>
             </div>
          </div>
        </section>
      </div>

    </div>
  </div>

   <footer></footer>

  <div class="row">
    <div class="twelve columns">
       <div id="virtualKeyboard"></div>

    </div>
  </div>



  </section>




  <!-- Included JS Files (Compressed) -->
  <script src="{{ MEDIA_URL }}javascripts/jquery.js"></script>
  <script src="{{ MEDIA_URL }}javascripts/boxlayout.js"></script>
  <script src="{{ MEDIA_URL }}javascripts/foundation.min.js"></script>
  <script src="{{ MEDIA_URL }}javascripts/jquery.foundation.orbit.js"></script>
  <script src="{{ MEDIA_URL }}javascripts/jsKeyboard.js"></script>
  <script src="{{ MEDIA_URL }}javascripts/app.js"></script>



  <script type="text/javascript">
     $(function () {jsKeyboard.init("virtualKeyboard"); });
     function showKeyboard(id) {
         clean($("#" + id));
         jsKeyboard.currentElement = $("#"+id);
         jsKeyboard.show();
     }
  </script>

  <script type="text/javascript">
     $(document).ready(function(){
        $('#slider').orbit();
     });

     $(function() {Boxlayout.init(); });
  </script>

</body>
</html>